:toc: macro
:toc-title:

= Docs Landing Page

https://app.netlify.com/sites/docs-rackspace-com/deploys[image:https://api.netlify.com/api/v1/badges/ea5a1331-0476-4664-83af-47ba3ac87159/deploy-status[title="Netlify Status"]] https://github.com/rackerlabs/docs-landing-page/graphs/contributors[image:https://img.shields.io/github/contributors-anon/rackerlabs/docs-landing-page?style=plastic[title=GitHub contributors]]

toc::[]

This repository contains the source code for https://docs.rackspace.com/ website.

The website is written in link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc], generated by using link:https://gohugo.io/[Hugo], and hosted on GitHub.

== Requirements

The Docs site runs on top of Hugo. To run an instance locally you need to either install
Hugo and AsciiDoctor locally.

=== Local set up

==== Install Hugo and AsciiDoctor locally

If you want to install the required tools, you must first install link://https://gohugo.io/[Hugo]
and have the `hugo` command available in your PATH. Use **Hugo version 0.78** or newer. You can
install `hugo` by using your system's package manager. For example, on OSX, type the following
command to install `hugo` with Homebrew:

```sh
brew install hugo
```

For more information about how to install Hugo please see the
link:https://gohugo.io/getting-started/installing/[installation documentation].

You also need Asciidoctor and Gem to run the local Docs site. Install those tools and verify them by
running the following commands:

`install asciidoctor: sudo gem install asciidoctor -N`
`verify asciidoctor -v`
`verify gem —help`

Alternatively, use the `npm install` command to install Asciidoctor by using link:https://rubygems.org[Ruby Gem]
and Bundler. You need to have the `gem` command in your path. For more information, see the
link:https://rubygems.org/pages/download[Ruby Gem installation docs].

====  Build the documentation locally

Build your content locally and check for build errors.

1. Change directory to the root directory of your document repository.
2. Run the following command:

```sh
npm run build:local
```

====  Start a local web server

To preview documents in a web browser such as Chrome, start the Hugo server on your device.

Hugo has a live `serve` command that runs a small, lightweight web server on your computer so you can
test your site locally without needing to upload it anywhere.  As you make changes to files in your project,
it rebuilds your project and reloads the browser for you.

To start the Hugo server, perform the following steps:

1. Change directory to the root directory of your document repository.
2. Run the following command:

Developer Docs runs on top of Webpack.

npm install`

`npm start`

The Hugo server displays some messages while it starts up.  The last line should be:

`Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop`

This running instance should support live reload. Changes you make to files should be automatically
updated in your running instance.

Some files may not be supported for live reload. If you are not automatically seeing your changes live
you may need to restart the server. You can restart the server by pressing 'ctrl-c' and running `npm start`
again.


You should now be able to access the developer docs homepage, for example, from: link:http://localhost:1313/[http://localhost:1313/]

This running instance should support live reload. Changes you make to files should be automatically
updated in your running instance.

Some files may not be supported for live reload. If you are not automatically seeing your changes live
you may need to restart the server. You can restart the server by pressing 'ctrl-c' and running 
`npm start` again.

==  Project directory structure

```
├── [archetypes]- Directory where you define the content, tags, categories, etc.
├── [content] - Directory that contains the content of the site.
├── [layouts] - Directory that contains Go HTML/template library used to template and format the site.
├── [public] - (Doesn't exist until generated) Directory that contains the generated content for the site. Should be part of your git.ignore file.
├── [static] - Directory for any static files to be compiled into the web site (style sheets, JavaScript, images, robots.txt, fav icons, etc.).
├── Makefile
├── config.toml - Main configuration file, where you define the web site title, URL, language, etc.
├── README.adoc (This file)
```

